#!/usr/bin/env python3
"""Build data/2025-data.json from the agreed schedule spreadsheet.

    python3 scripts/extract-2025-from-spreadsheet.py <schedule.xlsx> [out.json]

This is a ONE-OFF. Unlike every other report, the 2025 data does not come from
the joint Google Calendar - the calendar does not carry reliable custody
entries that far back - so it cannot be regenerated by scripts/refresh-all.mjs
and is deliberately left out of it. data/2025-data.json is committed as a
finished artefact and should only ever change if the spreadsheet itself is
corrected and this script re-run.

The spreadsheet's "Data" tab has one row per night:

    col 3  Date
    col 4  Mat     -> 1 when Mat has the children that night
    col 5  Claire  -> 1 when Claire does

Exactly one of the two is marked; the script fails loudly rather than guessing
if that stops being true, if a date inside the range is missing, or if a date
appears twice.
"""

import json
import sys
from collections import defaultdict
from datetime import date, timedelta

try:
    import openpyxl
except ImportError:
    sys.exit("openpyxl is required: pip install openpyxl")

START = date(2025, 5, 1)
END = date(2026, 1, 1)  # exclusive
NAMES = {"claire": "Claire", "parent2": "Mat"}


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    xlsx = sys.argv[1]
    out = sys.argv[2] if len(sys.argv) > 2 else "data/2025-data.json"

    ws = openpyxl.load_workbook(xlsx, data_only=True)["Data"]

    owners = {}
    for row in ws.iter_rows(min_row=2, values_only=True):
        cell = row[3]
        if not hasattr(cell, "date"):
            continue
        day = cell.date()
        if not (START <= day < END):
            continue
        mat, claire = row[4], row[5]
        if bool(mat) == bool(claire):
            sys.exit(f"{day}: expected exactly one of Mat/Claire to be marked, got {mat!r}/{claire!r}")
        if day in owners:
            sys.exit(f"{day}: appears more than once in the Data tab")
        owners[day] = "parent2" if mat else "claire"

    missing = []
    day = START
    while day < END:
        if day not in owners:
            missing.append(day.isoformat())
        day += timedelta(days=1)
    if missing:
        sys.exit(f"{len(missing)} date(s) missing from the Data tab, first few: {missing[:5]}")

    months = defaultdict(lambda: {"claire": 0, "parent2": 0})
    for day, owner in owners.items():
        months[day.strftime("%Y-%m")][owner] += 1

    month_rows = []
    for key in sorted(months):
        claire, parent2 = months[key]["claire"], months[key]["parent2"]
        total = claire + parent2
        month_rows.append({
            "month": key,
            "claire": claire,
            "parent2": parent2,
            "unassigned": 0,
            "totalDays": total,
            "clairePct": round(claire * 100 / total, 1),
            "parent2Pct": round(parent2 * 100 / total, 1),
        })

    claire = sum(m["claire"] for m in month_rows)
    parent2 = sum(m["parent2"] for m in month_rows)
    total = claire + parent2

    # The carry over is the imbalance the period ends on: how many nights one
    # parent is ahead going into the next year. Positive nights, plus who.
    lead = "claire" if claire >= parent2 else "parent2"
    result = {
        "static": True,
        "source": "schedule.01062026.xlsx, 'Data' tab - the agreed schedule spreadsheet",
        "note": (
            "Fixed history. Not produced by scripts/refresh-all.mjs and not "
            "derived from the joint Google Calendar - re-run "
            "scripts/extract-2025-from-spreadsheet.py only if the spreadsheet "
            "itself is corrected."
        ),
        "rangeStart": START.isoformat(),
        "rangeEnd": END.isoformat(),
        "names": NAMES,
        "months": month_rows,
        "totals": {
            "claire": claire,
            "parent2": parent2,
            "unassigned": 0,
            "clairePct": round(claire * 100 / total, 1),
            "parent2Pct": round(parent2 * 100 / total, 1),
        },
        "carryOver": {
            "owner": lead,
            "ownerName": NAMES[lead],
            "nights": abs(claire - parent2),
            "claire": claire,
            "parent2": parent2,
        },
    }

    with open(out, "w") as fh:
        json.dump(result, fh, indent=2)
        fh.write("\n")

    co = result["carryOver"]
    print(f"{out}: {len(owners)} nights, {START} to {END - timedelta(days=1)}")
    print(f"  Claire {claire} / Mat {parent2}  ({result['totals']['clairePct']}% / {result['totals']['parent2Pct']}%)")
    print(f"  carry over: {co['ownerName']} ahead by {co['nights']} nights")


if __name__ == "__main__":
    main()
